# Generated by Django 4.0.2 on 2022-02-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='case_image',
            new_name='cover',
        ),
    ]
