# Generated by Django 4.0.2 on 2022-02-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_favoriterecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite_recipe',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FavoriteRecipe',
        ),
    ]
